sudo: true

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t droid-docker-analyzer .
        - docker images
        - docker tag droid-docker-analyzer $DOCKER_USERNAME/droid-docker-analyzer
        - docker push $DOCKER_USERNAME/droid-docker-analyzer
    - stage: test basic tools
      script: 
        - docker run --rm $DOCKER_USERNAME/droid-docker-analyzer python -V
        - docker run --rm $DOCKER_USERNAME/droid-docker-analyzer java -version
        - docker run --rm $DOCKER_USERNAME/droid-docker-analyzer bash -c 'yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses'
